# Generated by Django 5.0.1 on 2024-01-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameraip',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
